project_id = "qsxoajvlubcoascenkqq"

[functions.send-contact-email]
verify_jwt = false

[functions.nhis-chat]
verify_jwt = false

[functions.get-mapbox-token]
verify_jwt = false

[functions.get-mapbox-directions]
verify_jwt = false
